export default {
  CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',

  LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',

  LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',

  START_LOADING: 'START_LOADING',
  END_LOADING: 'END_LOADING',
  REDIRECT: 'REDIRECT',

  ADD_USER: 'ADD_USER',
  FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',

  CREATE_TEMPLATE_REQUEST: 'CREATE_TEMPLATE_REQUEST',
  SAVE_TEMPLATE_REQUEST: 'SAVE_TEMPLATE_REQUEST',
  
  FETCH_TEMPLATES_SUCCESS: 'FETCH_TEMPLATES_SUCCESS',

  FETCH_TEMPLATE_SUCCESS: 'FETCH_TEMPLATE_SUCCESS',
  FETCH_TEMPLATE_FAILURE: 'FETCH_TEMPLATE_FAILURE',

  CHECK_AUTHENTICATION_SUCCESS: 'CHECK_AUTHENTICATION_SUCCESS'
};
