export default {
  CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',

  LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',

  LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',

  START_LOADING: 'START_LOADING',
  END_LOADING: 'END_LOADING',
  REDIRECT: 'REDIRECT',

  ADD_USER: 'ADD_USER',
  FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',

  CREATE_WEBSITE_REQUEST: 'CREATE_WEBSITE_REQUEST',
  SAVE_WEBSITE_REQUEST: 'SAVE_WEBSITE_REQUEST',
  SAVE_WEBSITE_SUCCESS: 'SAVE_WEBSITE_SUCCESS',

  FETCH_WEBSITES_SUCCESS: 'FETCH_WEBSITES_SUCCESS',

  FETCH_WEBSITE_SUCCESS: 'FETCH_WEBSITE_SUCCESS',
  FETCH_WEBSITE_FAILURE: 'FETCH_WEBSITE_FAILURE',
  FETCH_WEBSITE_EVENTS_SUCCESS: 'FETCH_WEBSITE_EVENTS_SUCCESS',
  FETCH_WEBSITE_EVENTS_FAILURE: 'FETCH_WEBSITE_EVENTS_FAILURE',

  SET_WEBSITE: 'SET_WEBSITE',

  CHECK_AUTHENTICATION_SUCCESS: 'CHECK_AUTHENTICATION_SUCCESS',
  CHECK_AUTHENTICATION_FAILURE: 'CHECK_AUTHENTICATION_FAILURE'
};
